In [57]:
# Task 1: Creating Arrays
# 1. Write a Python program to:
# o Create a 1D NumPy array of 10 integers ranging from 1 to 10.
# o Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9.
# o Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3).
# 2. Display the shape, size, and datatype of each array.

import numpy as np
array_1d = np.arange(1, 11)
array_2d = np.arange(1, 10).reshape(3, 3)
array_3d = np.random.rand(3, 5, 3)

# Display
def display_info(name, array):
    print(f"{name}:\n{array}")
    print(f"Shape: {array.shape}")
    print(f"Size: {array.size}")
    print(f"Data Type: {array.dtype}")
    print()

# Display
display_info("1D Array", array_1d)
display_info("2D Array", array_2d)
display_info("3D Array", array_3d)


1D Array:
[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Size: 10
Data Type: int32

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Data Type: int32

3D Array:
[[[0.75479419 0.08760203 0.9593155 ]
  [0.29497112 0.14293283 0.23235981]
  [0.52538539 0.86306692 0.01336224]
  [0.43864159 0.9218774  0.73391306]
  [0.59134426 0.2382835  0.20758339]]

 [[0.9904288  0.21091451 0.31876992]
  [0.42588434 0.24375477 0.76617005]
  [0.26567738 0.99814747 0.95294887]
  [0.46289016 0.4238573  0.39559225]
  [0.26307781 0.48133493 0.50846358]]

 [[0.27980233 0.89677315 0.57074686]
  [0.2473514  0.86381271 0.60129828]
  [0.20095765 0.93918138 0.27660512]
  [0.82955508 0.44826889 0.85087978]
  [0.99399375 0.08213869 0.89917309]]]
Shape: (3, 5, 3)
Size: 45
Data Type: float64



In [58]:
# Task 2: Array Indexing and Slicing
# 1. Create a NumPy array from the following list:
# data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# 2. Write a Python program to:
# o Retrieve the first three elements of the array.
# o Retrieve every alternate element of the array.
# o Reverse the array.
# 3. Perform the above operations and display the results

data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
array = np.array(data)
first_three = array[:3]
alternate_elements = array[::2]
reversed_array = array[::-1]

# Display 
print("Original Array:", array)
print("First Three Elements:", first_three)
print("Every Alternate Element:", alternate_elements)
print("Reversed Array:", reversed_array)


Original Array: [10 20 30 40 50 60 70 80 90]
First Three Elements: [10 20 30]
Every Alternate Element: [10 30 50 70 90]
Reversed Array: [90 80 70 60 50 40 30 20 10]


In [59]:
# Task 3: Mathematical Operations
# 1. Create two NumPy arrays, A and B, each with 5 random integers between 1 and 20.
# 2. Write a Python program to:
# o Add, subtract, multiply, and divide the two arrays element-wise.
# o Compute the dot product of the arrays.
# o Find the mean, median, standard deviation, and variance of array A.
# o Identify the maximum and minimum values in array B and their indices.

a = np.random.randint(1, 21, 5)
b = np.random.randint(1, 21, 5)

add = a + b
subtract = a - b
multiply = a * b
divide = a / b 

dot_product = np.dot(a, b)

mean_A = np.mean(a)
median_A = np.median(a)
std_A = np.std(a)
var_A = np.var(a)

max_B = np.max(b)
min_B = np.min(b)
max_index = np.argmax(b)
min_index = np.argmin(b)

# Display 
print("Array a:", a)
print("Array b:", b)

print("\nAddition:", add)
print("Subtraction:", subtract)
print("Multiplication:", multiply)
print("Division:", divide)

print("\nDot Product:", dot_product)

print("\nIn array a:")
print("Mean:", mean_A)
print("Median:", median_A)
print("Standard Deviation:", std_A)
print("Variance:", var_A)

print("\nIn array b:")
print("Maximum Value:", max_B, "at Index:", max_index)
print("Minimum Value:", min_B, "at Index:", min_index)


Array a: [ 4 12 16 20 19]
Array b: [15 19 11  1  6]

Addition: [19 31 27 21 25]
Subtraction: [-11  -7   5  19  13]
Multiplication: [ 60 228 176  20 114]
Division: [ 0.26666667  0.63157895  1.45454545 20.          3.16666667]

Dot Product: 598

In array a:
Mean: 14.2
Median: 16.0
Standard Deviation: 5.81033561853358
Variance: 33.760000000000005

In array b:
Maximum Value: 19 at Index: 1
Minimum Value: 1 at Index: 3


In [60]:

# Task 4: Reshaping and Transposing
# 1. Create a 1D NumPy array of 12 integers ranging from 1 to 12.
# 2. Write a Python program to:
# o Reshape the array into a 2D array of shape (4, 3).
# o Reshape the array into a 3D array of shape (2, 2, 3).
# o Transpose the reshaped 2D array and display its shape.

array_1d = np.arange(1, 13)
array_2d = array_1d.reshape(4, 3)
array_3d = array_1d.reshape(2, 2, 3)
transposed_2d = array_2d.T 

# Display 
print("1D Array:", array_1d)
print("\nReshaped 2D Array (4,3):\n", array_2d)
print("\nReshaped 3D Array (2,2,3):\n", array_3d)
print("\nTransposed 2D Array:\n", transposed_2d)
print("\nShape of Transposed Array:", transposed_2d.shape)


1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 2D Array (4,3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Reshaped 3D Array (2,2,3):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Transposed 2D Array:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

Shape of Transposed Array: (3, 4)


In [61]:
# Task 5: Boolean Masking and Filtering
# 1. Create a NumPy array with 15 random integers between 10 and 50.
# 2. Write a Python program to:
# o Find all elements greater than 25.
# o Replace all elements less than 30 with 0.
# o Count the number of elements divisible by 5.

array = np.random.randint(10,51,15)
greater = array[array > 25]
modified_array = np.where(array < 30,0,array)
count = np.sum(array%5==0)

# Display 
print("Array:", array)
print("\nElements greater than 25:", greater)
print("\nModified Array (values < 30 set to 0):", modified_array)
print("\nCount of elements divisible by 5:", count)

Array: [49 37 11 47 15 23 32 31 14 49 31 38 25 14 47]

Elements greater than 25: [49 37 47 32 31 49 31 38 47]

Modified Array (values < 30 set to 0): [49 37  0 47  0  0 32 31  0 49 31 38  0  0 47]

Count of elements divisible by 5: 2


In [62]:
# Task 6: Working with Built-in Functions
# 1. Use NumPy's built-in functions to:
# o Create an array of 10 equally spaced values between 0 and 1.
# o Create an identity matrix of size 4x4.
# o Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements.

arr = np.linspace(0, 1, 10) 
matrix = np.eye(4)
arr2 = np.random.randint(1,101,20)
sort_array = np.sort(arr2)
largest_element = sort_array[-5:]

# Display
print("An Array of 10 equally spaced values between 0 and 1:\n", array)
print("\n4x4 Identity Matrix:\n", matrix)
print("\nRandom Array of 20 integers between 1 and 100:", arr2)
print("\nSorted Array:", sort_array)
print("\nthe 5 largest elements in the array:", largest_element)

An Array of 10 equally spaced values between 0 and 1:
 [49 37 11 47 15 23 32 31 14 49 31 38 25 14 47]

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random Array of 20 integers between 1 and 100: [45 31 59 96 53 66 84 91 73 31 32 13 71 92 77  9 93 79 56 60]

Sorted Array: [ 9 13 31 31 32 45 53 56 59 60 66 71 73 77 79 84 91 92 93 96]

the 5 largest elements in the array: [84 91 92 93 96]


In [63]:
# Task 7: Generic
# 1. Create a Python program that:
# o Generates two large random arrays of size (100, 100).
# o Performs matrix multiplication on the two arrays.
# o Finds the determinant and inverse of the resulting matrix (if possible).
# o Measures the time taken to complete these operations.

import time
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)
st = time.time()
mm = np.matmul(A, B)
det = np.linalg.det(mm)
if det != 0:
    inverse = np.linalg.inv(mm)
    ins = ("Inverse computed .")
else:
    ins = ("Inverse not exist.")

et = time.time()
tt = et - st

# Display 
print("Matrix multiplication, determinant, and inverse completed.")
print(f"Determinant: {det:.4e}")
print(ins)
print(f"Total time taken: {tt:.4f} sec")



Matrix multiplication, determinant, and inverse completed.
Determinant: -7.5229e+48
Inverse computed .
Total time taken: 0.0301 sec
